/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4fd65d6b-3898-4129-9712-de687ad9aa8b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_uEeZqOq9b",
    "aws_user_pools_web_client_id": "5fagst079p2vrhu18j0vpieedl",
    "oauth": {}
};


export default awsmobile;
